default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  password: admin

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
